apiVersion: apps/v1
kind: Deployment
metadata:
  name: misfits-event-recommendation
  labels:
    app: misfits-event-recommendation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: misfits-event-recommendation
  template:
    metadata:
      labels:
        app: misfits-event-recommendation
    spec:
      containers:
      - name: misfits-event-recommendation
        image: dsaw1/misfits-event-recommendation:latest # Replace with your registry
        ports:
        - containerPort: 8000
        env:
        - name: CHROMA_HOST
          value: "43.205.192.16"
        - name: CHROMA_PORT
          value: "8000"
        - name: TRANSFORMERS_OFFLINE
          value: "1"
        - name: HF_HUB_OFFLINE
          value: "1"
        - name: OPENAI_BASE_URL
          value: "https://integrate.api.nvidia.com/v1"
        - name: OPENAI_API_KEY
          value: "nvapi-YOUR-API-KEY-HERE"  # Replace with your actual NVIDIA API key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health/readiness
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: misfits-event-recommendation-service
spec:
  selector:
    app: misfits-event-recommendation
  ports:
    - protocol: TCP
      port: 8001        # external port
      targetPort: 8000  # internal container port
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: misfits-event-recommendation-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: misfits-event-recommendation
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80